#!/usr/bin/env node
/**
 * Docs generator.
 *
 * Emits:
 *   docs/tools.md     — every MCP tool
 *   docs/resources.md — MCP resource URIs + templates
 *   docs/cli.md       — every CLI command tree
 *
 * Run:  node scripts/gen-docs.mjs   (requires prior tsup build)
 */

import { spawn } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

const ROOT = resolve(import.meta.dirname, "..");
const DOCS = resolve(ROOT, "docs");
mkdirSync(DOCS, { recursive: true });

// ---- MCP ----

async function generateMcpDocs() {
  const transport = new StdioClientTransport({
    command: "node",
    args: [resolve(ROOT, "dist/mcp.js")],
    env: {
      ...process.env,
      COOLIFY_BASE_URL: "https://example.invalid",
      COOLIFY_TOKEN: "docs-probe-token",
    },
  });
  const client = new Client({ name: "docs-gen", version: "0" }, {});
  await client.connect(transport);

  const { tools } = await client.listTools();
  const { resources } = await client.listResources();
  const { resourceTemplates } = await client.listResourceTemplates();
  await client.close();

  const toolsByGroup = new Map();
  for (const t of tools.sort((a, b) => a.name.localeCompare(b.name))) {
    const group = classifyTool(t.name);
    if (!toolsByGroup.has(group)) toolsByGroup.set(group, []);
    toolsByGroup.get(group).push(t);
  }

  const lines = [
    "# MCP Tools",
    "",
    "> Auto-generated by `scripts/gen-docs.mjs`. Do not hand-edit.",
    "",
    `**Total tools:** ${tools.length}`,
    "",
    `**Generated:** ${new Date().toISOString()}`,
    "",
    "## Index",
    "",
  ];
  for (const group of Array.from(toolsByGroup.keys()).sort()) {
    lines.push(`- [${group}](#${slug(group)}) — ${toolsByGroup.get(group).length} tools`);
  }
  lines.push("");

  for (const group of Array.from(toolsByGroup.keys()).sort()) {
    lines.push(`## ${group}`);
    lines.push("");
    for (const t of toolsByGroup.get(group)) {
      lines.push(`### \`${t.name}\``);
      lines.push("");
      if (t.title) lines.push(`**Title:** ${t.title}`);
      lines.push("");
      lines.push(`**Description:** ${t.description ?? "—"}`);
      lines.push("");
      if (t.inputSchema) {
        lines.push("**Input schema:**");
        lines.push("");
        lines.push("```json");
        lines.push(JSON.stringify(t.inputSchema, null, 2));
        lines.push("```");
        lines.push("");
      }
    }
  }
  writeFileSync(resolve(DOCS, "tools.md"), `${lines.join("\n")}\n`);
  console.log(`✓ wrote docs/tools.md — ${tools.length} tools`);

  const resLines = [
    "# MCP Resources",
    "",
    "> Auto-generated by `scripts/gen-docs.mjs`. Do not hand-edit.",
    "",
    `**Static resources:** ${resources.length}`,
    "",
    `**Templates:** ${resourceTemplates.length}`,
    "",
    `**Generated:** ${new Date().toISOString()}`,
    "",
    "## Static",
    "",
    "| URI | Title | Description | MIME |",
    "|---|---|---|---|",
    ...resources.map(
      (r) => `| \`${r.uri}\` | ${r.name ?? "—"} | ${r.description ?? "—"} | ${r.mimeType ?? "—"} |`,
    ),
    "",
    "## Templates",
    "",
    "| URI template | Title | Description | MIME |",
    "|---|---|---|---|",
    ...resourceTemplates.map(
      (r) =>
        `| \`${r.uriTemplate}\` | ${r.name ?? "—"} | ${r.description ?? "—"} | ${r.mimeType ?? "—"} |`,
    ),
    "",
  ];
  writeFileSync(resolve(DOCS, "resources.md"), `${resLines.join("\n")}\n`);
  console.log(
    `✓ wrote docs/resources.md — ${resources.length} resources + ${resourceTemplates.length} templates`,
  );
}

function classifyTool(name) {
  if (name.startsWith("system_")) return "System";
  if (/github|_gh_/.test(name)) return "GitHub Apps";
  if (name.startsWith("hetzner_") || name === "create_hetzner_server") return "Hetzner";
  if (name.includes("cloud")) return "Cloud tokens";
  if (/(^|_)application(s|_|$)|_app($|_)|_apps?$|_app_/.test(name)) return "Applications";
  if (
    /database|_db|postgres|mysql|mariadb|mongodb|redis|clickhouse|dragonfly|keydb|_backup/.test(
      name,
    )
  )
    return "Databases";
  if (/service|_svc/.test(name)) return "Services";
  if (name.includes("deployment") || name === "trigger_deploy") return "Deployments";
  if (name.includes("project")) return "Projects";
  if (/(^|_)server(s|_|$)|server_resources|server_domains|validate_server/.test(name))
    return "Servers";
  if (name.includes("team")) return "Teams";
  if (name.includes("key")) return "Private keys";
  if (name === "search_resources" || name === "list_resources") return "Search & resources";
  return "Composite / misc";
}

function slug(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// ---- CLI ----

async function generateCliDocs() {
  const root = await runHelp([]);
  for (const child of root.subcommands) {
    await walk(child, [child.name]);
  }

  const lines = [
    "# CLI Reference",
    "",
    "> Auto-generated by `scripts/gen-docs.mjs`. Do not hand-edit.",
    "",
    `**Generated:** ${new Date().toISOString()}`,
    "",
  ];
  renderNode(root, lines, []);
  writeFileSync(resolve(DOCS, "cli.md"), `${lines.join("\n")}\n`);
  console.log("✓ wrote docs/cli.md");
}

async function walk(node, path) {
  const help = await runHelp(path);
  node.options = help.options;
  node.usage = help.usage;
  node.description = help.description;
  node.subcommands = help.subcommands;
  for (const child of node.subcommands) {
    await walk(child, [...path, child.name]);
  }
}

function runHelp(argvPath) {
  return new Promise((resolvePromise) => {
    const p = spawn("node", [resolve(ROOT, "dist/cli.js"), ...argvPath, "--help"], {
      env: {
        ...process.env,
        COOLIFY_BASE_URL: "https://example.invalid",
        COOLIFY_TOKEN: "x",
      },
    });
    let out = "";
    p.stdout.on("data", (c) => {
      out += c.toString();
    });
    p.on("close", () => resolvePromise(parseHelp(out, argvPath)));
  });
}

function parseHelp(text, argvPath) {
  const lines = text.split("\n");
  const node = {
    name: argvPath.at(-1) ?? "coolify-11d",
    path: argvPath,
    description: "",
    usage: "",
    options: [],
    subcommands: [],
  };
  let section = null;
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (/^Usage:/.test(line)) {
      node.usage = line.replace(/^Usage:\s*/, "");
      section = null;
      continue;
    }
    if (/^Options:/.test(line)) {
      section = "options";
      continue;
    }
    if (/^Commands:/.test(line)) {
      section = "commands";
      continue;
    }
    if (section === "options" && /^\s{2,}-/.test(line)) {
      const match = line.match(/^\s+([^\s].*?)\s{2,}(.*)$/);
      if (match) node.options.push({ flag: match[1], help: match[2] });
      continue;
    }
    if (section === "commands" && /^\s{2,}\S/.test(line)) {
      const match = line.match(/^\s+(\S+)(?:\s\S+)*\s{2,}(.*)$/);
      if (match && match[1] !== "help") {
        node.subcommands.push({
          name: match[1],
          description: match[2],
          options: [],
          subcommands: [],
        });
      }
      continue;
    }
    if (!section && line && argvPath.length === 0) {
      if (!node.description && /^[A-Z]/.test(line.trim())) node.description = line.trim();
    }
  }
  return node;
}

function renderNode(node, lines, path) {
  const full = ["coolify-11d", ...path].join(" ");
  const depth = Math.min(path.length + 1, 5);
  lines.push(`${"#".repeat(depth + 1)} \`${full}\``);
  lines.push("");
  if (node.description) {
    lines.push(node.description);
    lines.push("");
  }
  if (node.usage) {
    lines.push(`**Usage:** \`${node.usage}\``);
    lines.push("");
  }
  if (node.options?.length) {
    lines.push("**Options:**");
    lines.push("");
    for (const o of node.options) {
      lines.push(`- \`${o.flag}\` — ${o.help}`);
    }
    lines.push("");
  }
  for (const child of node.subcommands ?? []) {
    renderNode(child, lines, [...path, child.name]);
  }
}

// ---- main ----

try {
  await generateMcpDocs();
  await generateCliDocs();
  console.log("\n✓ all docs regenerated under docs/");
} catch (err) {
  console.error("✗ docs generation failed:", err);
  process.exit(1);
}
